Skil 160
Lunatic-Labs/rubricapp pull request #508
Opened 2023-10-19 16:10 UTC by malloc-nbytes

Added functionality to add either students or TA's for bulk uploading.
LMS ID for students is taken as optional.
Changed the csv/xlsx parsing to "Last name, first name", email, role, (optional) LMS ID.
Added helper functions for any current and future iterations of bulk uploading.

2023-10-31 20:49 UTC, Wrimo commented
I also noticed the program can partially upload a list of users. There are four users listed and only the last one is poorly formatted, the first three will be created but the last one will not. I believe it is only supposed to upload if all the users are valid.

2023-11-01 23:17 UTC, brianlugo1 requested changes

2023-11-01 23:17 UTC, brianlugo1 commented on BackEndFlask/controller/Routes/Bulk_upload_routes.py
> +        createBadResponse("Unsuccessfully uploaded a .csv or .xlsx file!", "Wrong Format", "uesrs")
Typo “uesrs”!

2023-11-01 23:17 UTC, brianlugo1 commented on BackEndFlask/Functions/test_files/test_randAssignTeams.py
> +            # raise
We can go ahead and delete this line!

2023-11-06 21:00 UTC, Wrimo requested changes

2023-12-19 15:45 UTC, Wrimo requested changes
Almost ready to be merged. Just a few things mostly about comments I think should be changed first.

2023-12-19 15:45 UTC, Wrimo commented on BackEndFlask/Functions/addStudentsAndAssignTeams.py
> +    new_user_course: List[int]: A list of *user_ids* that were created.
Is this comment correct? new_user_course and new_user_ids are both lists of user_ids that were created?

2023-12-19 15:45 UTC, Wrimo commented on BackEndFlask/Functions/addStudentsAndAssignTeams.py
> +        # TODO: Create the user_course.
Comment is out of date.

2023-12-19 15:45 UTC, Wrimo commented on BackEndFlask/Functions/genericImport.py
> +    owner_id: int:  The user_id of the owner of the course.
I believe you could remove the owner_id parameter and instead get it from the database by finding the owner_id of the course with id course_id. Not a huge deal but would simplify calling the function and potentially calling it without matching course_id and owner_id.

2023-12-19 15:45 UTC, Wrimo commented on BackEndFlask/Functions/test_files/test_genericImport.py
> +# test_file_not_found()
Why are there lots of commented out tests? Are they broken or deprecated? Can they be deleted?

2024-01-05 05:41 UTC, closed without merging