Skil 166 - Skill Builder Redesign
Lunatic-Labs/rubricapp pull request #515
Opened 2023-11-15 17:20 UTC by aldiux4you

Merged SKIL-170 branch to develop the Global CSS Style.  
Merged the SKIL-161-Confirm-Team branch to include components and the Build Team Page. 

- Moved the current logic of Navbar into AppState.js
- Created a Global Navbar that displays the logo and profile/settings.
- Created BasicTabs.js components to conditionally render Roster, Teams, and Assessment Task after navigating into a course. 
- Created Reusable Components (BackButton, BackButtonResource, CourseInfo, CustomDataTable, MainHeader).
- Add Global CSS Classes to SBStyles.css
- Refactored and redesigned logic for Add/Edit Course
- Moved logic of functions from AppState.js to its children components.

2023-11-16 00:13 UTC, Wrimo requested changes
First, I wanted to compliment how good the UI redesign looks. I poked around on the site a bit, and it looks very professional. 

Second, I don't really have much to say about the code. It generally all looks really good to my very limited knowledge of how to write React. The one thing I noticed that will need to be changed is that the new React code is not using the updates I made in the Code Refactor branch to avoid passing functions around and instead pass a reference to the navbar. All of that will need to be changed before merging into master.

2023-12-19 14:06 UTC, Wrimo requested changes

2023-12-19 15:32 UTC, brianlugo1 commented on BackEndFlask/controller/Routes/User_routes.py
> +                else:
The following code is flawed and has been refactored in SKIL-174. Once we merge this pull request into master before merging SKIL-174, the issue will be resolved!

2023-12-19 15:32 UTC, Wrimo approved these changes
LGTM

2023-12-19 15:36 UTC, brianlugo1 approved these changes
@sah0017 LGTM!

2023-12-19 16:34 UTC, merged