Final Update to Drop User Functionality on DropUser-Test
Lunatic-Labs/rubricapp pull request #516
Opened 2023-11-30 22:24 UTC by mehrab7

Upon my last testing on 11/30, you are able to click on the Drop User button on Edit User and hit save to drop the user. This changes the "active" value to false in the specific UserCourse table. When looking at the roster page, the user does not appear due to the filter that filters out inactive users. The user is not deleted, but they should not and do not appear on the roster page.

2023-12-04 17:33 UTC, Wrimo requested changes

2023-12-04 17:33 UTC, Wrimo commented on BackEndFlask/controller/Routes/User_routes.py
> +        # replace json with usercourse schema dump with necessary info, and replace users at the end with usercourses
I believe this comment is out of date.

2023-12-04 17:33 UTC, Wrimo commented on BackEndFlask/models/schemas.py
> +    active = db.Column(db.Boolean, nullable=True)
Why allow active to be nullable? What does it mean if a user has a null active? Seems like we should be able to say all users are either active or not.

2023-12-04 17:33 UTC, Wrimo commented on BackEndFlask/models/user_course.py
> +        # return UserCourse.query.filter_by(user_id=user_id).all()
No need to keep the old code in a comment. 

Additionally, there are lots of comment that seem like development notes, not documentation for future developers. I would either remove these or reword them to make the intent clear.

2023-12-04 17:33 UTC, Wrimo commented on BackEndFlask/core/__init__.py
> +CORS(app, resources={r"/*": {"origins": "*"}})
Question out of my own ignorance: what does CORS do and why do we need it?

2023-12-19 14:03 UTC, Wrimo approved these changes
I just made my recommended changes to this branch, and it is ready to be merged once @malloc-nbytes and @brianlugo1 get a chance to look at it.

2023-12-21 14:37 UTC, brianlugo1 approved these changes
@sah0017 LGTM!

2023-12-21 14:38 UTC, brianlugo1 commented
@sah0017 This pull request has received two approved code reviews! I am going to go ahead and merge this branch into master!

2023-12-21 14:38 UTC, merged