SKIL-555
Lunatic-Labs/rubricapp pull request #804
Opened 2024-12-21 00:36 UTC by jcallison1

TODOs Completed:
- Redesigned the CompleteAssessmentTask family of files to use a new class based Unit system.
- Cleaned up CompleteAssessmentTask code and made it easier to read.
- Added extensive comments to help future developers work on the CompleteAssessmentTask system with less friction.

2024-12-21 04:05 UTC, aparriaran approved these changes
@sah0017 LGTM

2024-12-21 04:35 UTC, sah0017 requested changes
There is (still?) a bug in the saving of data.  I opened the demo data for Critical Thinking Assessment, Maria only has 2 categories filled in.  I filled in the remaining categories, hit Done, she went to green.  I edited Wade Cooper, put data in the first 2 categories.  The Autosaving message popped up.  Went back and hit View, looked at Maria, the categories I had filled in were not there, and only the first of the two categories I filled in for Wade was saved.  I don't know if this was a preexisting bug (I think it may have been).  

I don't see where you merged master back into SKIL-555 after you finished.  Would you do that and make sure everything merges appropriately?

2024-12-21 17:48 UTC, jcallison1 commented
For some reason I couldn't reproduce the exact issue you described, however I did fix two highly related issues I found. Hopefully one of those was the root cause of the issue you described. I will now work on merging master into our branch. Unfortunately that may take a while, as I was never able to get MySQL working on my computer after the MySQL migration.

2024-12-21 18:04 UTC, jcallison1 commented
I have merged master and everything still seems to be working correctly.

2024-12-23 02:42 UTC, sah0017 commented
@jcallison1 Did you run npm install?  I'm getting a lot of npm package errors when I run your code like it is still using the code/packages from the previous versions before I updated them.

2024-12-23 02:51 UTC, sah0017 commented
I'm still having the issue that I described above.  It doesn't appear to save for me past the first category tab, or it isn't retrieving it, one or the other.  You're not having that issue in your environment?

2024-12-23 03:25 UTC, sah0017 commented
I had fixed the constraint issue for adding an assessment, but not for updating an assessment, so I went ahead and applied that fix in your branch.  That resolved the issue I was having with it saving subsequent categories.

2024-12-23 03:30 UTC, sah0017 reviewed
LGTM (after fixing DB constraint issue)

2024-12-23 03:30 UTC, sah0017 approved these changes

2025-01-09 19:52 UTC, merged